### ISSUE TITLE
Accept inputs for `collection_type: list:paired` for workflow testing

### ISSUE THREAD

**Issue by tshtatland** [galaxyproject/planemo#1018]
Enable specifying in *test.yml a set of inputs for `collection_type: list:paired`. A list of dataset pairs is very frequently used as workflow input by our users who analyze NGS paired-end reads.

I am using `planemo test` to test a simple example workflow: select_paired_list_fastq, https://usegalaxy.eu/u/tshtatland/w/selectpairedlistfastq . I was looking for something like this to be possible to specify in *test.yml:
```
- doc: "Test sample data for select_paired_list_fastq_wo_param workflow"
  job:
    input_paired_list_fastq:
      class: Collection
      collection_type: list:paired
      elements:
        - identifier: test1
          class: Collection
          collection_type: paired
          elements:
            - identifier: forward
              class: File
              location: https://zenodo.org/record/3875556/files/test1.1.fastq
              filetype: fastqsanger
            - identifier: reverse
              class: File
              location: https://zenodo.org/record/3875556/files/test1.2.fastq
              filetype: fastqsanger
        - identifier: test2
          class: Collection
          collection_type: paired
          elements:
            - identifier: forward
              class: File
              location: https://zenodo.org/record/3875556/files/test2.1.fastq
              filetype: fastqsanger
            - identifier: reverse
              class: File
              location: https://zenodo.org/record/3875556/files/test2.2.fastq
              filetype: fastqsanger
```
