### ISSUE TITLE
Proposal: dynamic download of test data

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/planemo#1268]
I would like to propose the development of a new feature. On our CI using planemo we have some logic so that for any tool directory that has a `get_test_data.sh` or so bash script the CI executes that and brings in the test data, which avoids having the test data (which sometimes can be heavy) on the tool's git repo. I wonder if such functionality being internalised into planemo would be well received?

For planemo I envision instead having a YAML file of the kind:

```yaml
- tool: tool_id
   test_files:
   - file_name: test_file_1.txt
      url: https://some-url-for.the/file
      md5: ....
```

then planemo, prior to testing each tool, could download files. Let me know if this would be acceptable.
