### ISSUE TITLE
planemo lint workflow tests improvement

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/planemo#1413]
This test:
```yml
- doc: Test outline for scrna-seq-fastq-to-matrix-10X-cellplex.ga
  job:
    fastq PE collection GEX:
      class: Collection
      collection_type: list:paired
      elements:
      - class: Collection
        type: paired
        identifier: subsample
        elements:
        - identifier: forward
          class: File
          location: https://zenodo.org/records/10229382/files/subSample_GEX_R1.fastq.gz
          filetype: fastqsanger.gz
        - identifier: reverse
          class: File
          location: https://zenodo.org/records/10229382/files/subSample_GEX_R2.fastq.gz
          filetype: fastqsanger.gz
   ...
  outputs:
    CITE-seq-Count report:
      class: Collection
      collection_type: list
      elements:
        identifier: subsample
        class: File
        asserts:
          - that: "has_line"
            line: "CITE-seq-Count Version: 1.4.4"
          - that: "has_line"
            line: "Reads processed: 1171367"
...
```
Passes the workflow_lint but the test will fail with the following error message:
`No path specified for expected output file [CITE-seq-Count report]`

The correct grammar is:
```
...
    CITE-seq-Count report:
      class: Collection
      collection_type: list
      element_tests:
        subsample:
          asserts:
            - that: "has_line"
              line: "CITE-seq-Count Version: 1.4.4"
            - that: "has_line"
              line: "Reads processed: 1171367"
...
```
