### ISSUE TITLE
planemo test_workflow with list:list collections

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/planemo#1414]
Could you tell me if the grammar is correct?:
```
    Seurat input for gene expression (filtered):
      class: Collection
      collection_type: list:list
      element_tests:
        subsample:
          element_tests:
            matrix:
              asserts:
                - has_line:
                  line: "55141 353 1026324"
            barcodes:
              asserts:
                - has_line:
                  line: "AAACGAAAGCATGCAG"
            genes:
              asserts:
                - has_line:
                  line: "ENSMUSG00000102693	4933401J01Rik"
```

When I use this grammar and I change the line to something silly, the test continue to pass. Also when I change the name of the elements to something silly, it still passes. Therefore, I wonder if it is my grammar which is wrong or planemo which does not support list:list tests.
