### ISSUE TITLE
Getting ShedVersion error on unmodified tools that reside in the same directory than modified tools

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/planemo#1525]
Today, on an update to a tool inside a directory that has unmodified sister tools, I started getting these type of errors in the CI:

```
ERROR (ShedVersion): scanpy_plot_scrublet: version 1.9.3+galaxy0 is less or equal than version of the latest installable revision 1.9.3+galaxy0
```

from the unmodified tools. This comes from calling in the CI:

```
    - name: Planemo lint
      uses: galaxyproject/planemo-ci-action@v1
      id: lint
      with:
        mode: lint
        fail-level: ${{ env.FAIL_LEVEL }}
        repository-list: ${{ needs.setup.outputs.repository-list }}
        tool-list: ${{ needs.setup.outputs.tool-list }}
```

Maybe an issue from the most recent planemo version where some changes where made to the ShedVersion part (if I read the release correctly)? Thanks!
