### ISSUE TITLE
global base path for shed_upload include relative paths

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#160]
I'm trying to replace a manual process for preparing tar-balls to push to the Tool Shed, however by using a common top level ``test-data/`` (and ``tool-data/``) folder this is harder than expected.

Current manual process as documented in this tool's README file:

```
$ tar -czf venn_list.tar.gz tools/venn_list/README.rst tools/venn_list/venn_list.* tools/venn_list/tool_dependencies.xml test-data/magic.pdf test-data/venn_list.tabular test-data/rhodopsin_proteins.fasta
$ tar -tzf venn_list.tar.gz
tools/venn_list/README.rst
tools/venn_list/venn_list.py
tools/venn_list/venn_list.xml
tools/venn_list/tool_dependencies.xml
test-data/magic.pdf
test-data/venn_list.tabular
test-data/rhodopsin_proteins.fasta
```

I have been able to get the desired output (ignoring the order, #159) with a complicated ``.shed.yml`` entry like this:

```
include:
- source: README.rst
  destination: tools/venn_list/README.rst
- source: venn_list.py
  destination: tools/venn_list/venn_list.py
- source: venn_list.xml
  destination: tools/venn_list/venn_list.xml
- source: tool_dependencies.xml
  destination: tools/venn_list/tool_dependencies.xml
- source: ../../test-data/magic.pdf
  strip_components: 2
- source: ../../test-data/venn_list.tabular
  strip_components: 2
- source: ../../test-data/rhodopsin_proteins.fasta
  strip_components: 2
```

Giving:

```
$ planemo shed_upload --tar_only  ~/repositories/pico_galaxy/tools/venn_list 
cp /tmp/tmpybJqwL shed_upload.tar.gz
(.venv)[galaxy@ppserver planemo]$ tar -tzf /tmp/tmpybJqwL
tools/
tools/venn_list/
tools/venn_list/venn_list.py
tools/venn_list/tool_dependencies.xml
tools/venn_list/README.rst
tools/venn_list/venn_list.xml
test-data/
test-data/rhodopsin_proteins.fasta
test-data/magic.pdf
test-data/venn_list.tabular
```

I would like to use something along these lines in the ``.shed.yml`` file:

```
#All include paths from two levels up (i.e. prefix with ../../ to find the file)
include_offset: 2
include:
- tools/venn_list/README.rst
- tools/venn_list/venn_list.py
- tools/venn_list/venn_list.xml
- tools/venn_list/tool_dependencies.xml
- test-data/magic.pdf
- test-data/venn_list.tabular
- test-data/rhodopsin_proteins.fasta
```

**Comment by erasche** [comment]
Wouldn't it just be easier to symlink test-data?

**Comment by peterjc** [comment]
So have ``~/repositories/pico_galaxy/tools/venn_list/test-data`` pointed at ``~/repositories/pico_galaxy/test-data``,

```
$ cd ~/repositories/pico_galaxy/tools/venn_list/
$ ln -s ../../test-data/ test-data
```

And then use something like this in ``.shed.yml``,

```
include:
- README.rst
- venn_list.py
- venn_list.xml
- tool_dependencies.xml
- test-data/magic.pdf
- test-data/venn_list.tabular
- test-data/rhodopsin_proteins.fasta
```

That works:

```
$ planemo shed_upload --tar_only  ~/repositories/pico_galaxy/tools/venn_list 
cp /tmp/tmp3GYrUC shed_upload.tar.gz
$ tar -xvf /tmp/tmp3GYrUC
venn_list.py
tool_dependencies.xml
README.rst
test-data/
test-data/rhodopsin_proteins.fasta
test-data/magic.pdf
test-data/venn_list.tabular
venn_list.xml
```

This means a one-off upheaval in the tool history on the Tool Shed (the main files would move, e.g. ``tools/venn_list/venn_list.xml`` --> ``venn_list.xml``), and for me (making the symlinks).

Essentially this means pushing the directory structure outlined here https://github.com/galaxy-iuc/standards/blob/master/docs/best_practices/repositories.rst (over the approach I'm currently using based on how things were setup back before the Tool Shed existed).

I don't like the symlink idea though; but I do have a lot of common test files used in multiple Tool Shed repositories (e.g. ``test-data/rhodopsin_proteins.fasta`` and ``test-data/magic.pdf`` in this example).

**Comment by jmchilton** [comment]
I guess @erasche was advocating linking in just the test-data needed (there will be an option in planemo to auto-infer the test-data at some point so it would be moot either way). 

I like the new structure - Greg and Dan always advocated one tool per repository and I think planemo is getting close to making that... well less say a lot less painful for developers. In that world view - I am not sure a ``tools`` directory makes a lot of sense. I feel like each repository should have one *primary* artifact - packages a ``tool_dependencies.xml``, suites ``repository_dependencies.xml`` and a Tool XML file for a tool directory - all in the root.

That said - I don't want planemo to force a world view - just sort of subtlely hint at it. Would globs have simplified your original include statements?

```
include:
- source: *
  destination: tools/venn_list/
test-data:
  include:
  - ../../test-data/magic.pdf
  - ../../test-data/venn_list.tabular
  - ../../test-data/rhodopsin_proteins.fasta
```

The glob above should work (let me know if it doesn't) - ``test-data`` directive doesn't exist yet - but makes sense to add it to me.
