### ISSUE TITLE
Configurable tool-data for shed resolution.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#162]
Add a ``tool_data`` directive to ``.shed.yml`` with the obvious default.

```
tool_data:  ; totally optional, compeltely inferred from IUC "best practices"
  conf: ../path/to/tool_data_table_conf.xml ; ./tool_data_table_conf.xml.sample by default
  auto_locs: true ; true by default
  include:
    - ../../tool-data/foo.loc    ; manually specify tool-data contents if ``auto_locs: False``
```

Useful to custom repository layouts (See #160) but also for de-multiplexing tool directories.
