### ISSUE TITLE
Configurable test-data for shed resolution.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#163]
Add a ``test_data`` directive to ``.shed.yml`` with the obvious defaults.

```
test_data:  ; totally optional, compeltely inferred from IUC "best practices"
  auto: false  ; inferring test data has some corner cases and would be off by default I guess
                     ; and this dirctory would just be auto detected for "best practices" repos
  include:
    - 1.fasta    ; manually specify tool-data contents if ``auto_locs: False``
  base: ../../test-data
```

Useful to custom repository layouts (See #160) but also for de-multiplexing tool directories.
