### ISSUE TITLE
linting: Document how to use planemo lint in a git pre-commit hook

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#94]
Once planemo has a useful lint command, we should all start using it with every commit automatically via a pre-commit hook.

Depending on the lint speed, this may require some cleverness to only test tools/files which have changed since the last commit - much like how pep8 checking is often restricted to only the Python files with changes, e.g. https://github.com/cbrueffer/pep8-git-hook

**Comment by jmchilton** [comment]
I like this idea a lot. My proposed implementation would be more than just documentation however given the complexity of repositories such as ``tools-devteam`` and ``tools-iuc``.

Implementation Suggestion:

Implement a ``planemo hook_init`` that will add the hook script to a repository and create a ``.planemo_hook.yml`` file if not present. The hook script will simply run a ``hook_check`` command that looks at the optional ``.planemo_hook.yml`` file and does the linting described within.

An absent ``.planemo_hook.yml`` file corresponds to just effectively running ``planemo shed_lint --tools --recursive`` over the whole repository - which will lints all repositories and all tools it finds within them. This will fail for tools-devteam and tools-iuc still - so ``.planemo_hook.yml`` can be used to do more targeted testing.

```
# Look at all shed artifacts but skip digging into tools.
shed:
 - paths: .
   recursive: true
   tools: false
tool:
 # Do full linting on select repositories that are up to date.
 - paths: tools/bwa,tool_collections/vcflib/vcf2tsv
 # Do less strict linting on other repositories
 - paths: tools/bowtie2 
   skip_formatting: false
 # Simply look for serious errors on older repositories
 - paths: tools/emboss_5/emboss_5
   fail_level: error
```

In addition to making things more lax ``.planemo.yml`` could be used to make things more stringent as well - specifically I am imagining a ``xsd: true`` field that would enable the new tool XSD checks on discovered tools.
